kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: llg-pod-exec
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: llg-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llg-pod-exec
subjects:
  - kind: ServiceAccount
    name: liquibase-lock-guard
    namespace: {{ .Release.Namespace }}
